In [1]:
# changing categorical data which is not nominal to numerical data using Ordinal Encoding



## using one hot encoding

In [1]:
## use the frequent categories and group the rest as 'other'
# reduce the number of categories by grouping infrequent categories into a single category called 'Other'.

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('cars.csv')

In [5]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [6]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [7]:
df['brand'].nunique()

32

In [9]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [10]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [13]:
## one hot encoding using pandas

one_hot_encoded_df_pandas = pd.get_dummies(df, columns=['brand', 'fuel', 'owner'], drop_first=True)
one_hot_encoded_df_pandas.head()

,km_driven,selling_price,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,...,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,145500,450000,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1,120000,370000,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
2,140000,158000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
3,127000,225000,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,120000,130000,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [14]:
### k-1 encoding

pd.get_dummies(df['fuel'], drop_first=True)

      Diesel    LPG  Petrol
0       True  False   False
1       True  False   False
2      False  False    True
3       True  False   False
4      False  False    True
...      ...    ...     ...
8123   False  False    True
8124    True  False   False
8125    True  False   False
8126    True  False   False
8127    True  False   False

[8128 rows x 3 columns]

In [15]:
## we can not take pandas get dummies for large number of categories as it will create too many columns
#also pandas get dummies does not handle unseen categories in test data

In [21]:
# we use sklearn OneHotEncoder for that
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('price', axis=1), df['price'], test_size=0.2, random_state=42)

KeyError: "['price'] not found in axis"

In [18]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [19]:
X_train.head()

NameError: name 'X_train' is not defined